# Generated by Django 4.1 on 2022-08-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_alter_cart_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
