# Generated by Django 4.1 on 2022-08-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
