# Generated by Django 4.1 on 2022-08-04 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0007_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user']},
        ),
    ]
