# Generated by Django 4.1 on 2022-08-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_ordered']},
        ),
        migrations.AddField(
            model_name='cart',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
