# Generated by Django 4.1 on 2022-08-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0009_alter_cart_options_cart_date_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
