# Generated by Django 4.1 on 2022-08-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0010_alter_product_options_product_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-user']},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date_ordered',
        ),
    ]
