# Generated by Django 4.1 on 2022-08-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0013_alter_category_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
