# Generated by Django 4.1 on 2022-08-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0014_alter_category_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=2500)),
                ('date_send', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-date_send'],
            },
        ),
    ]
