# Generated by Django 4.1 on 2022-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
