# Generated by Django 4.1 on 2022-08-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0016_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
