# Generated by Django 4.1 on 2022-08-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0017_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
