# Generated by Django 4.1 on 2022-08-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0019_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
