# Generated by Django 4.1 on 2022-08-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0020_alter_userprofile_options_userprofile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
